target 'TMDB' do

  pod 'Alamofire'
  pod 'IQKeyboardManager'
  pod 'SkeletonView'
  pod 'SwifterSwift'
  pod 'Kingfisher'

  target 'TMDBTests' do
    inherit! :search_paths
  end

  target 'TMDBUITests' do
  end

end
